# Generated by Django 4.1.5 on 2023-01-30 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("None", "Default"),
                            ("1", "Debito"),
                            ("2", "Boleto"),
                            ("3", "Financiamento"),
                            ("4", "Credito"),
                            ("5", "Emprestimo"),
                            ("6", "Vendas"),
                            ("7", "Ted"),
                            ("8", "Doc"),
                            ("9", "Aluguel"),
                        ],
                        default="None",
                        max_length=25,
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cpf", models.CharField(max_length=11)),
                ("card", models.CharField(max_length=12)),
                ("hour", models.TimeField()),
                ("store_owner", models.CharField(max_length=155)),
                ("store_name", models.CharField(max_length=155)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_stores",
                        to="stores.stores",
                    ),
                ),
            ],
        ),
    ]
